# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JobMe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JobMe
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Firebase/Auth'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'

  target 'JobMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
